name = "game4-worker"
main = "src/index.ts"
compatibility_date = "2025-09-16"

[[d1_databases]]
binding = "DB"
database_name = "game4_leaderboard"
# 部署后使用 `wrangler d1 list` 查到真实 ID 并替换
database_id = "c6bfc858-c3f2-4093-a36f-ac8095252bc7"

[[kv_namespaces]]
binding = "CACHE"
# 创建后填入 KV 命名空间 ID
id = "929645906d8a4a7f91a92086780e9501"

[vars]
# 允许的前端域名（逗号分隔）
ALLOWED_ORIGINS = "https://game4.biboran.top"


